-- Add extended profile fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(300) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country CHAR(2) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS organization VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS position VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS imgurl TEXT DEFAULT NULL;
